name: flake-check
on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches:
      - 'main'

jobs:
  check:
    runs-on: yolofanhd-github
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Create dummy hardware-configuration.nix
        run: |
          cat > hardware-configuration.nix <<EOF
          { config, lib, pkgs, modulesPath, ... }: {
            imports = [ (modulesPath + "/installer/scan/not-detected.nix") ];
            fileSystems."/" = {
              device = "/dev/disk/by-label/nixos";
              fsType = "ext4";
            };
          }
          EOF
      - name: Check flake
        run: nix flake check
