name: update-flake-lock
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: "0 0 * * 1,4" # Run twice a week

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Install Nix
        uses: cachix/install-nix-action@V27
      - name: Update flake
        run: nix flake update
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7.0.8
        with:
          commit-message: "ci(flake.lock): automatic update"
          branch: ci/flake-lock-update
          title: "ci(flake.lock): automatic update"
          body: updated flake.lock
          assignees: yolofanhd
          reviewers: yolofanhd
